# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-06 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181206_0640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wheel',
            table='axf_wheel',
        ),
    ]
