# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181213_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='trackid1',
            new_name='childcid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='trackid2',
            new_name='childcid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='trackid3',
            new_name='childcid3',
        ),
    ]
