# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181213_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='prouductid1',
            new_name='productid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='prouductid2',
            new_name='productid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='prouductid3',
            new_name='productid3',
        ),
    ]
